<?php
require_once("../include/session.php");
require_once("../include/sessionmanagementgarage.php");
require_once("../include/dbconnection.php");
//email notification
require "../vendor/autoload.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

if (isset($_GET['bookingId'])) {
    $bookingId = $_GET['bookingId'];
}else {
    echo "bookingid value not found.";
}

    //get cancel booking details 
    $sqlget = "SELECT * FROM booking as b, customer as c 
    WHERE b.bookingId='$bookingId'
    AND b.cusId=c.cusId";
    $resultget = mysqli_query($conn, $sqlget);

    
    if (mysqli_num_rows($resultget) > 0) {
          
            $rowresult = mysqli_fetch_assoc($resultget);
            
            $email=$rowresult['cusEmail']; 
            $cus_fname=$rowresult['cusFname']; 
            $bookingdate=$rowresult['bookingDate']; 
            $timeslot=$rowresult['timeSlot']; 
            $cusid=$rowresult['cusId']; 
            $garageid=$rowresult['garageId'];
            $vehiid=$rowresult['vehiId'];  
            $payid=$rowresult['payId']; 
            $paystatus=$rowresult['pStatus']; 
        }
                                                
            $currentDate= date("Y-m-d");
            $cofficerfname=$_SESSION['cfname'];
    
            //insert details to the cancel booking table
            $sql = "INSERT INTO cancel_booking (cancelId, bookingId, bookingDate, timeSlot, cusId, garageId, vehiId, payId, pStatus, cancelDate, cancelBy) VALUES ('','$bookingId', '$bookingdate', '$timeslot','$cusid','$garageid','$vehiid','$payid','$paystatus','$currentDate','$cofficerfname')";
            $result = mysqli_query($conn, $sql) or die(mysqli_error($conn));
        
             //error handelling
            if (!$result) {
               die("Error: " . mysqli_error($conn));
             }

            //delete booking from booking and issue_certicaten table
            if ($result) {

           //delete records from both tables
             $sqldelete =   "DELETE booking, issued_certificate
                            FROM booking
                            INNER JOIN issued_certificate ON booking.bookingId = issued_certificate.bookingId
                            WHERE booking.bookingId ='$bookingId'";

           
            $resultdelete=mysqli_query($conn,$sqldelete) or die(mysqli_error($conn));
                
                //error handelling
                if (!$resultdelete) {
                   die("Error: " . mysqli_error($conn));
                }

              //email notification
              $mail = new PHPMailer(true);
              $mail ->isSMTP();
              $mail ->SMTPAuth = true;

              //gmail stmp server
              $mail ->Host = "smtp.gmail.com";
              $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
              $mail ->Port = 587;
             
              $mail ->Username = "wcvfeisproject@gmail.com";
              $mail ->Password = "xzll euej xvli frza";

              $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
              $mail ->addAddress($email,$cus_fname);
              $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
              date_default_timezone_set('Asia/kolkata');
              $mail->isHTML(true); 

            
              $mail->Body = '<p><strong>Your reservation has been cancelled due to an unavoidable reason. Sorry for the inconvenience. Please contact your garage if you have made any payments about the booking. </strong></p>' .
                          '<p>This email is automatically generated by the system. Please do not reply.</p>' .
                          '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';


              //error handeling
              try {
                  $mail->send();
                  //  message to the user
                      $msg ="Booking ( Booking ID:". $bookingId . ") canceled successfully.";	
                      header("Location:g-bookingmgt.php?id=$msg"); 
                      exit();
              } catch (Exception $e) {
               
                  $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
                  header("Location:g-bookingmgt.php?id=$msg");
              }
               exit();
              
 } else {
    $msg = "Failed to cancel booking"; 	
    header("Location:g-bookingmgt.php?id=$msg"); 
    exit();
}
     
mysqli_close($conn);


?>
