<?php 
require_once("../include/session.php");
require_once("../include/sessionmanagementgarage.php");
require_once("../include/dbconnection.php");
//email notification
require "../vendor/autoload.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

if (isset($_SESSION['unic'])) {
    $usernic = $_SESSION['unic'];
    $aprovedBy=$_SESSION['cfname'];
    
   
} else {
    echo "NIC value not found.";
}

 if ($_SERVER["REQUEST_METHOD"] == "POST") {
    if (isset($_POST["new_status"])) {
        $new_status = $_POST["new_status"];
        $bookingid = $_POST["bookingid"];
        $cus_email = $_POST["cusEmail"];
        $cus_fname = $_POST["cusFname"];
        $cusid = $_POST["cusId"];
        $vehiid = $_POST["vehiid"]; 

    // already paid
    $sql = "SELECT * FROM payment WHERE bookingId = '$bookingid'";
    $result = mysqli_query($conn, $sql);
    
        if (mysqli_num_rows($result) > 0) {
            
            $msg = "Already paid for the booking";
            $redirectUrl = "g-bookingmgt.php?bookingid=$bookingid&vehiId=$vehiId&id=" . urlencode($msg);
            header("Location: $redirectUrl");
        } else {
            
                // No paid
                // Add database query to save payment information
                $amount ="1000" ;
                $payType = "on-site";
                $currentDate= date("Y-m-d");
         

                    $sqlinsert = "INSERT INTO payment (payId, bookingId, vehiId, cusId, amount, payType, pDate, aprovedBy ) VALUES ('','$bookingid', '$vehiid','$cusid','$amount','$payType','$currentDate','$aprovedBy')";
                    $resultinsert = mysqli_query($conn, $sqlinsert);

                    // get last id
                    $payId = mysqli_insert_id($conn);
                   
                    
                    // update issued_certificate table
                    $sqlupdate = "UPDATE booking SET payId = '$payId',
                                  pStatus='$new_status' 
                                  WHERE bookingId = $bookingid";
                    
                    $resultupdate=mysqli_query($conn,$sqlupdate);
                 
                      //email notification
                      $mail = new PHPMailer(true);
                      $mail ->isSMTP();
                      $mail ->SMTPAuth = true;
                      
                      $mail ->Host = "smtp.gmail.com";
                      $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
                      $mail ->Port = 587;
                      
                      $mail ->Username = "wcvfeisproject@gmail.com";
                      $mail ->Password = "xzll euej xvli frza";

                      $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
                      $mail ->addAddress($cus_email,$cus_fname);
                      $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
                      date_default_timezone_set('Asia/kolkata');
                      $mail->isHTML(true); 

                      $mail->Body = '<p><strong>"Payment successful. Your booking ID :'. $bookingid.' "</strong></p>' .
                                  '<p>This email is automatically generated by the system. Please do not reply.</p>' .
                                  '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';

                      //error handeling
                      try {
                          $mail->send();
                                
                                $msg = "Payment successful. booking ID :$bookingid";
                                $redirectUrl = "g-bookingmgt.php?garageId=$garageId&vehiId=$vehiId&id=" . urlencode($msg);
                                 header("Location: $redirectUrl");
                      } catch (Exception $e) {
                          
                          $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
                          header("Location:../g-bookingmgt.php?id=$msg");
                      }
                      
                    
                      exit();
            }

            mysqli_close($conn);
    }else {
         echo "value not found.";
    }
}
?>