<?php 
require_once("../include/session.php");
require_once("../include/sessionmanagementgarage.php");
require_once("../include/dbconnection.php");
//email notification
require "../vendor/autoload.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

if (isset($_SESSION['unic'])) {
    $usernic = $_SESSION['unic'];
    $requestedBy=$_SESSION['ofname'];
    $useremail=$_SESSION['email'];
    
   
} else {
    echo "NIC value not found.";
}


 if ($_SERVER["REQUEST_METHOD"] == "POST") {
    if (isset($_POST["request_year"])) {
        $request_year = $_POST["request_year"];
        $garage_Id = $_POST["garageId"];
        
                $rStatus ="Pending" ;
                $pStatus ="Pending" ;
                $currentDate= date("Y-m-d");
         

                    $sqlinsert = "INSERT INTO garage_renew (renewId, garageId, requestYear, rStatus, pStatus, requstedBy, requestedDate) VALUES ('','$garage_Id', '$request_year','$rStatus','$pStatus','$requestedBy','$currentDate')";
                    $resultinsert = mysqli_query($conn, $sqlinsert);
                 
                      //email notification
                      $mail = new PHPMailer(true);
                      $mail ->isSMTP();
                      $mail ->SMTPAuth = true;

                      
                      $mail ->Host = "smtp.gmail.com";
                      $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
                      $mail ->Port = 587;
                   
                      $mail ->Username = "wcvfeisproject@gmail.com";
                      $mail ->Password = "xzll euej xvli frza";

                      $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
                      $mail ->addAddress($useremail,$requestedBy);
                      $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
                      date_default_timezone_set('Asia/kolkata');
                      $mail->isHTML(true); 
                     
                      $mail->Body = '<p><strong>"Renew request send successfully."</strong></p>' .
                                  '<p>This email is automatically generated by the system. Please do not reply.</p>' .
                                  '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';


                      //error handeling
                      try {
                          $mail->send();
                              
                                $msg = "Renew request send successfully";
                                $redirectUrl = "g-renew-registration.php?usernic=$usernic&id=" . urlencode($msg);
                                 header("Location: $redirectUrl");
                      } catch (Exception $e) {
                          
                          $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
                          $redirectUrl = "g-renew-registration.php?usernic=$usernic&id=" . urlencode($msg);
                          header("Location: $redirectUrl");
                      }
                      
                    
                      exit();
            }
            
        
    }else {
         echo "value not found.";
    }
    mysqli_close($conn);
?>