
<?php
require_once("../include/sessionmanagementgarage.php");
require_once("../include/dbconnection.php");
//email notification
require "../vendor/autoload.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

if ($_SERVER["REQUEST_METHOD"] == "POST") {
   
    if (isset($_POST["update"])) {
        $update_ststus = $_POST["update"];
        $booking_id = $_POST["booking_id"];
        $cus_email = $_POST["cusEmail"];
        $cus_fname = $_POST["cusFname"];
        $booing_date = $_POST["bdate"];
        $booking_time = $_POST["btime"];
     
  
    }else {
        echo "value not found.";
}
}

if ($update_ststus == 'Pending'){
        $sqlup = "UPDATE booking SET bStatus = 'Confirm' WHERE bookingId = $booking_id";
        
        $resultin=mysqli_query($conn,$sqlup) or die(mysqli_error($conn));

         //email notification
         $mail = new PHPMailer(true);
         $mail ->isSMTP();
         $mail ->SMTPAuth = true;

         $mail ->Host = "smtp.gmail.com";
         $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
         $mail ->Port = 587;
        
         $mail ->Username = "wcvfeisproject@gmail.com";
         $mail ->Password = "xzll euej xvli frza";

         $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
         $mail ->addAddress($cus_email,$cus_fname);
         $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
         date_default_timezone_set('Asia/kolkata');
         $mail->isHTML(true); 

         $mail->Body = '<p><strong> Your booking has been confirmed. Take your vehicle for an inspection on'. $booing_date. 'at' . $booking_time.'.</strong></p>' .
                     '<p>This email is automatically generated by the system. Please do not reply.</p>' .
                     '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';


         //error handeling
         try {
             $mail->send();
            
                 $msg ="( Booking ID:". $booking_id . ") Booking confirmed ";	
                 header("Location:g-bookingmgt.php?id=$msg"); 
                 exit();
         } catch (Exception $e) {
             
             $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
             header("Location:g-bookingmgt.php?id=$msg");
         }
         exit();

   
}elseif ($update_ststus == 'Confirm') {
    $sqlup = "UPDATE booking SET bStatus = 'Complete' WHERE bookingId = $booking_id";
   
    $resultin=mysqli_query($conn,$sqlup) or die(mysqli_error($conn));

         //email notification
         $mail = new PHPMailer(true);
         $mail ->isSMTP();
         $mail ->SMTPAuth = true;

         $mail ->Host = "smtp.gmail.com";
         $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
         $mail ->Port = 587;
       
         $mail ->Username = "wcvfeisproject@gmail.com";
         $mail ->Password = "xzll euej xvli frza";

         $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
         $mail ->addAddress($cus_email,$cus_fname);
         $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
         date_default_timezone_set('Asia/kolkata');
         $mail->isHTML(true); 

         $mail->Body = '<p><strong> Your booking has been Completed. Take your vehicle for an inspection on.</strong></p>' .
                     '<p>This email is automatically generated by the system. Please do not reply.</p>' .
                     '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';


         //error handeling
         try {
             $mail->send();
            
                 $msg ="( Booking ID:". $booking_id . ") Booking confirmed ";	
                 header("Location:g-bookingmgt.php?id=$msg"); 
                 exit();
         } catch (Exception $e) {
          
             $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
             header("Location:g-bookingmgt.php?id=$msg");
         }
         exit();


}

header('Location: g-bookingmgt.php');
?>
