<?php
  require_once("../include/session.php");
require_once("../include/sessionmanagementgarage.php");
require_once("../include/dbconnection.php");
//email notification
require "../vendor/autoload.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    
    if (isset($_POST["new_status"])) {
        $update_ststus = $_POST["inspspec_status"];
        $booking_id = $_POST["booking_id"];
        $cus_email = $_POST["cusEmail"];
        $cus_fname = $_POST["cusFname"];
        $new_status = $_POST["new_status"];
        
        
    }else {
        echo "value not found.";
}
}

if ($update_ststus == 'Pending'){
    //new state send by form value
        if($new_status == 'Pass'){ 
            $sqlup = "UPDATE booking SET vehiInspection = 'Pass' WHERE bookingId = $booking_id";
           
            $resultin=mysqli_query($conn,$sqlup) or die(mysqli_error($conn));

              //email notification
              $mail = new PHPMailer(true);
              $mail ->isSMTP();
              $mail ->SMTPAuth = true;

              $mail ->Host = "smtp.gmail.com";
              $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
              $mail ->Port = 587;
     
              $mail ->Username = "wcvfeisproject@gmail.com";
              $mail ->Password = "xzll euej xvli frza";

              $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
              $mail ->addAddress($cus_email,$cus_fname);
              $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
              date_default_timezone_set('Asia/kolkata');
              $mail->isHTML(true); 

              $mail->Body = '<p><strong> Your vehicle inspection is Passed. Please make the Payment. Your e-certification issuing fee is Rs.1000/-. You can pay through the system *Log in to the system and visit Check e-certificate issuing status* or pay at garage Premises..</strong></p>' .
                          '<p>This email is automatically generated by the system. Please do not reply.</p>' .
                          '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';


              //error handeling
              try {
                  $mail->send();
                  
                      $msg ="( Booking ID:". $booking_id . ") vehicle inspection is Passed";	
                      header("Location:g-bookingmgt.php?id=$msg"); 
                      exit();
              } catch (Exception $e) {
    
                  $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
                  header("Location:g-bookingmgt.php?id=$msg");
              }
              exit();



            
        }elseif ($new_status == 'Reject'){
            $sqlup = "UPDATE booking SET vehiInspection = 'Reject' WHERE bookingId = $booking_id";
           
            $resultin=mysqli_query($conn,$sqlup) or die(mysqli_error($conn));

                //email notification
                $mail = new PHPMailer(true);
                $mail ->isSMTP();
                $mail ->SMTPAuth = true;

                $mail ->Host = "smtp.gmail.com";
                $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
                $mail ->Port = 587;
                
                $mail ->Username = "wcvfeisproject@gmail.com";
                $mail ->Password = "xzll euej xvli frza";

                $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
                $mail ->addAddress($cus_email,$cus_fname);
                $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
                date_default_timezone_set('Asia/kolkata');
                $mail->isHTML(true); 

                $mail->Body = '<p><strong>Your vehicle inspection is rejected. Please make the necessary adjustments to your vehicle and submit it to your garage for re-inspection within 2 weeks and get your e-certificate of Vehivle Fitness. </strong></p>' .
                            '<p>This email is automatically generated by the system. Please do not reply.</p>' .
                            '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';


                //error handeling
                try {
                    $mail->send();
                   
                        $msg ="( Booking ID:". $booking_id . ") vehicle inspection is rejected";	
                        header("Location:g-bookingmgt.php?id=$msg"); 
                        exit();
                } catch (Exception $e) {
               
                    $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
                    header("Location:g-bookingmgt.php?id=$msg");
                }
                exit();

        }
        
}elseif ($update_ststus == 'Reject') {
    $sqlup = "UPDATE booking SET vehiInspection = 'Pass' WHERE bookingId = $booking_id";
    
    $resultin=mysqli_query($conn,$sqlup) or die(mysqli_error($conn));

    //email notification
    $mail = new PHPMailer(true);
    $mail ->isSMTP();
    $mail ->SMTPAuth = true;

    $mail ->Host = "smtp.gmail.com";
    $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
    $mail ->Port = 587;
   
    $mail ->Username = "wcvfeisproject@gmail.com";
    $mail ->Password = "xzll euej xvli frza";

    $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
    $mail ->addAddress($cus_email,$cus_fname);
    $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
    date_default_timezone_set('Asia/kolkata');
    $mail->isHTML(true);

    $mail->Body = '<p><strong> Your vehicle inspection is Passed. Please make the Payment. Your e-certification issuing fee is Rs.1000/-. You can pay through the system *Log in to the system and visit Check e-certificate issuing status* or pay at garage Premises..</strong></p>' .
                '<p>This email is automatically generated by the system. Please do not reply.</p>' .
                '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';


    //error handeling
    try {
        $mail->send();
    
            $msg ="( Booking ID:". $booking_id . ") vehicle inspection is Passed";	
            header("Location:g-bookingmgt.php?id=$msg"); 
            exit();
    } catch (Exception $e) {
       
        $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
        header("Location:g-bookingmgt.php?id=$msg");
    }
    exit();

}
header('Location: g-bookingmgt.php');
?>



