
<?php
require_once("../../include/session.php");
require_once("../../include/dbconnection.php");
require "../../vendor/autoload.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;


if (isset($_POST["submit"])){
    if($_POST['email']== "" || $_POST['password']== ""){
        $msg=("User Name or Password can not be empty....");
        header("Location:../c-login.php?id=$msg");	
		exit();
    
    }

$email=mysqli_real_escape_string($conn,$_POST['email']);
$pass=mysqli_real_escape_string($conn,$_POST['password']);
$epass=sha1($pass);
//check un and pw in db
$sql=mysqli_query($conn,"SELECT * FROM cus_login WHERE email='$email' AND pwd='$epass'");
$count=mysqli_num_rows($sql);

//echo $count;

 
if($count!=0){
	$sqlinfo="SELECT * FROM customer as c, cus_login as l 
	WHERE l.email ='$email' AND c.cusId=l.cusId";

	$resultinfo=mysqli_query($conn,$sqlinfo);
	$rowinfo=mysqli_fetch_array($resultinfo);
	
//set session variable	
	$_SESSION['fname']=$rowinfo['cusFname'];
	$_SESSION['lname']=$rowinfo['cusLname'];
	$nic=$_SESSION['nic']=$rowinfo['cusNic'];
	$_SESSION['email']=$rowinfo['email'];
	$_SESSION['pno']=$rowinfo['cusPno'];
	$_SESSION['cid']=$rowinfo['cusId'];
    $_SESSION['password']=$rowinfo['pwd'];
	$_SESSION['sid']=session_id(); 
	
//email notification
	$mail = new PHPMailer(true);
	$mail ->isSMTP();
	$mail ->SMTPAuth = true;

//gmail use as smtp server
	$mail ->Host = "smtp.gmail.com";
	$mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
	$mail ->Port = 587;
// set username and app password
	$mail ->Username = "wcvfeisproject@gmail.com";
	$mail ->Password = "xzll euej xvli frza";

	$mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
	$mail ->addAddress($rowinfo['email'],$rowinfo['cusFname']);
	$mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
	date_default_timezone_set('Asia/kolkata');
	$mail->isHTML(true); // set email format to HTML

	// HTML for the email body
	$mail->Body = '<p><strong>You are successfully logged in.</strong></p>' .
				'<p>This email is automatically generated by the system. Please do not reply.</p>' .
				'<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';

	//$mail ->send();
	//header("Location:../c-dashboard.php");

	//error handeling
	try {
		$mail->send();
		// sent successfully
		header("Location:../c-dashboard.php");
	} catch (Exception $e) {
		// could not be sent
		$msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
		header("Location:../c-dashboard.php?id=$msg");
	}
	
	
}else{
	$msg=("Invalid User Name or Password....");
	header("Location:../c-login.php?id=$msg");
	exit();
    
}
}
mysqli_close($conn);

?>

