<?php
require_once("../../include/dbconnection.php");
require "../../vendor/autoload.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

if (isset($_POST["submit"])){
    $cus_fname=$_POST['fname'];
    $cus_lname=$_POST['lname'];
    $nic=$_POST['nic'];
    $cus_pno=$_POST['pno'];
    $email=$_POST['email'];
    $password=$_POST['password'];
    $passwordsha=sha1($_POST['password']);
    
    $sql_nic = "SELECT * FROM customer WHERE cusNic='$nic'";
    $sql_e = "SELECT * FROM cus_login WHERE email='$email'";
    $res_nic = mysqli_query($conn, $sql_nic);
    $res_e = mysqli_query($conn, $sql_e);

    //validation
        if (!preg_match("/^[a-zA-Z ]*$/",$cus_fname)) {  
            $msg = "Only alphabets are allowed for First Name...";  
            header("Location:../c-signup.php?id=$msg");
            exit();
        
        } elseif (!preg_match("/^[a-zA-Z ]*$/",$cus_lname)) {  
            $msg = "Only alphabets are allowed for Last Name..";  
            header("Location:../c-signup.php?id=$msg");
            exit();

        } elseif (!preg_match ("/^[0-9]*$/", $cus_pno)) {  
            $msg = "Only numeric value is allowed for Phone Number..";  
            header("Location:../c-signup.php?id=$msg");
            exit();

        } elseif (strlen ($cus_pno) != 10) {  
            $msg  = "Mobile Number must contain 10 digits.."; 
            header("Location:../c-signup.php?id=$msg"); 
            exit();

        } elseif (!preg_match ("/^[0-9]*$/", $nic)) {  
            $msg = "Only numeric value is allowed for NIC..";  
            header("Location:../c-signup.php?id=$msg");
            exit();

        } elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $msg = "Invalid email format.."; 
            header("Location:../c-signup.php?id=$msg");
            exit();

        } elseif (strlen($password) <= 8) {
            $msg  = 'Password should be at least 8 characters in length..';
            header("Location:../c-signup.php?id=$msg"); 
            exit();

        }elseif(mysqli_num_rows($res_nic) > 0){
            $msg = "Sorry... NIC already exists.."; 	
            header("Location:../c-signup.php?id=$msg"); 
            exit();

        }elseif(mysqli_num_rows($res_e) > 0){
            $msg = "Sorry... email already exists.."; 	
            header("Location:../c-signup.php?id=$msg"); 
            exit();
            
        }else{

        $sqlin="INSERT INTO customer (cusId, cusFname, cusLname, cusNic, cusPno, cusEmail ) VALUES ('','$cus_fname','$cus_lname','$nic','$cus_pno','$email')";
        $resultin=mysqli_query($conn,$sqlin) or die(mysqli_error($conn));
        
        $cus_id=mysqli_insert_id($conn);
        $sqllog="INSERT INTO cus_login (email, pwd, cusId) VALUES ('$email','$passwordsha','$cus_id')";
        $resultlog=mysqli_query($conn,$sqllog) or die(mysqli_error($conn));

        //email notification
        $mail = new PHPMailer(true);
        $mail ->isSMTP();
        $mail ->SMTPAuth = true;

        $mail ->Host = "smtp.gmail.com";
        $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
        $mail ->Port = 587;
       
        $mail ->Username = "wcvfeisproject@gmail.com";
        $mail ->Password = "xzll euej xvli frza";

        $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
        $mail ->addAddress($email,$cus_fname);
        $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
        date_default_timezone_set('Asia/kolkata');
        $mail->isHTML(true); 

     
        $mail->Body = '<p><strong>You are successfully registered to the Vehicle Fitness e-certificate issuing system.</strong></p>' .
                    '<p>This email is automatically generated by the system. Please do not reply.</p>' .
                    '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';

        
        //error handeling
            try {
            $mail->send();
           
            $msg = "You are Successfully registered."; 	
            header("Location:../c-login.php?id=$msg");
        } catch (Exception $e) {
           
            $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
            header("Location:../c-login.php?id=$msg");
        }
        exit();
    }
}
mysqli_close($conn);
?>