<?php
require_once("../../include/session.php");
require_once("../../include/dbconnection.php");
require "../../vendor/autoload.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

if (isset($_POST["submit"])){
   if($_POST['email']== "" || $_POST['password']== ""){
       $msg=("User Name or Password can not be empty....");
       header("Location:../d-login.php?id=$msg");	
	   exit();
    
   }

$email=mysqli_real_escape_string($conn,$_POST['email']);
$pass=mysqli_real_escape_string($conn,$_POST['password']);
$role=mysqli_real_escape_string($conn,$_POST['role']);
$epass=sha1($pass);

if($role=="Admin"){

	$sqlinfoadmin="SELECT * FROM staff_login as sl
	WHERE sl.email ='$email'AND sl.pwd='$pass'";
	
	$resultinfoadmin=mysqli_query($conn,$sqlinfoadmin);

	if (!$resultinfoadmin) {
		die("Error: " . mysqli_error($conn));
	}
	
	$rowinfoadmin=mysqli_fetch_array($resultinfoadmin);
	$_SESSION['dmtStaffId']="admin";
	$_SESSION['stfRole']="admin";
	$_SESSION['stfFname']="admin";
	$_SESSION['stflLname']="admin";
	$_SESSION['stfNic']="admin";
	$_SESSION['email']=$rowinfoadmin['email'];
    $_SESSION['password']=$rowinfoadmin['pwd'];
	$_SESSION['siddmt']=session_id(); 
	
	header("Location:../d-dashboard.php");
	exit();


}

$sql=mysqli_query($conn,"SELECT * FROM  dmt_staff as ds, staff_login as sl
	WHERE sl.email ='$email'AND sl.pwd='$epass' AND ds.dmtStaffId=sl.dmtStaffId AND ds.stfRole='$role'");

$count=mysqli_num_rows($sql);

//echo $count;
if($count!=0){
	$sqlinfo="SELECT * FROM dmt_staff as ds, staff_login as sl
	WHERE ds.dmtStaffId=sl.dmtStaffId AND ds.stfRole='$role'";
	
	$resultinfo=mysqli_query($conn,$sqlinfo);

	if (!$resultinfo) {
		die("Error: " . mysqli_error($conn));
	}
	
	$rowinfo=mysqli_fetch_array($resultinfo);
	

	$_SESSION['dmtStaffId']=$rowinfo['dmtStaffId'];
	$_SESSION['stfRole']=$rowinfo['stfRole'];
	$_SESSION['stfFname']=$rowinfo['stfFname'];
	$_SESSION['stflLname']=$rowinfo['stflLname'];
	$stfNic=$_SESSION['stfNic']=$rowinfo['stfNic'];
	$_SESSION['email']=$rowinfo['email'];
    $_SESSION['password']=$rowinfo['pwd'];
	$_SESSION['siddmt']=session_id(); 

	
	//email notification
	$mail = new PHPMailer(true);
	$mail ->isSMTP();
	$mail ->SMTPAuth = true;

	//gmail stmp server
	$mail ->Host = "smtp.gmail.com";
	$mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
	$mail ->Port = 587;
	
	$mail ->Username = "wcvfeisproject@gmail.com";
	$mail ->Password = "xzll euej xvli frza";

	$mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
	$mail ->addAddress($rowinfo['email'],$rowinfo['stfFname']);
	$mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
	date_default_timezone_set('Asia/kolkata');
	$mail->isHTML(true); 

	
	$mail->Body = '<p><strong>You are successfully logged in.</strong></p>' .
				'<p>This email is automatically generated by the system. Please do not reply.</p>' .
				'<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';

	//$mail ->send();
	//header("Location:../c-dashboard.php");

	//error handeling
	try {
		$mail->send();
		
		header("Location:../d-dashboard.php");
	} catch (Exception $e) {
		
		$msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
		header("Location:../d-dashboard.php?id=$msg");
	}
	
	
	
}else{
	$msg=("Invalid User Name or Password or Role....");
	header("Location:../dmtwp-login.php?id=$msg");
	exit();
    
}
}


?>

