<?php                 
require_once("../include/sessionmanagement.php");
require_once("../include/dbconnection.php");
require "../vendor/autoload.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

if (isset($_SESSION['nic'])) {
    $nic = $_SESSION['nic'];
    $cusid=$_SESSION['cid'];
    $cus_fname=$_SESSION['fname'];
    $email=$_SESSION['email'];
    
    //echo $nic;
    //echo $cusid;
} else {
    echo "NIC value not found.";
}
   
if (isset($_POST["vehiId"])) {
    $vehiId = $_POST["vehiId"];
    $garageId = $_POST["garageId"];
    
//echo $vehiId;
}else {
    echo "value not found.";

}
                     
if ($_SERVER["REQUEST_METHOD"] == "POST") {
// user input 
$date = $_POST["date"];
$time = $_POST["time"];

$date = mysqli_real_escape_string($conn, $date);
$time = mysqli_real_escape_string($conn, $time);

// Check availability 
$sql = "SELECT * FROM booking WHERE bookingDate = '$date' AND timeSlot = '$time' AND garageId = '$garageId'";
$result = mysqli_query($conn, $sql);

if (mysqli_num_rows($result) > 0) {
    // booking exists date
    $msg = "Sorry, the selected date and time slot are not available. Please choose a different time slot or date.";
    $redirectUrl = "c-booking.php?garageId=$garageId&vehiId=$vehiId&id=" . urlencode($msg);
    header("Location: $redirectUrl");
} else {
    // no booking found 
    $sql = "SELECT * FROM booking WHERE vehiId = '$vehiId'";
    $result = mysqli_query($conn, $sql);

    if (mysqli_num_rows($result) > 0) {
        // booking exists same vehicle
        $msg = " Your vehicle has another booking ";
        $redirectUrl = "c-booking.php?garageId=$garageId&vehiId=$vehiId&id=" . urlencode($msg);
        header("Location: $redirectUrl");
    } else {
        // no booking same date, time, and vehicle
                        
            $sql = "INSERT INTO booking (bookingId, bookingDate, timeSlot, bStatus, bConfirm, cusId, garageId, vehiId, payId, pStatus, vehiInspection ) VALUES ('','$date', '$time','Pending','0','$cusid','$garageId','$vehiId','0','Pending','Pending')";
            $result = mysqli_query($conn, $sql);

            // last id
            $bookingId = mysqli_insert_id($conn);

          
            $sql2 = "INSERT INTO issued_certificate (issueId, fitnessId, fStatus, inspectionId, iStatus,cofficerId,bookingId, vehiId, issueDate, issueTime) VALUES ('', '0','Pending','0','Pending','0','$bookingId', '$vehiId','0','0')";
            $result2= mysqli_query($conn, $sql2);

                //email notification
                $mail = new PHPMailer(true);
                $mail ->isSMTP();
                $mail ->SMTPAuth = true;

                $mail ->Host = "smtp.gmail.com";
                $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
                $mail ->Port = 587;
                
                $mail ->Username = "wcvfeisproject@gmail.com";
                $mail ->Password = "xzll euej xvli frza";

                $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
                $mail ->addAddress($email,$cus_fname);
                $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
                date_default_timezone_set('Asia/kolkata');
                $mail->isHTML(true); 

                $mail->Body = '<p><strong>Your reservation has been received. You will get a booking confirmation email as soon as possible. .</strong></p>' .
                            '<p>This email is automatically generated by the system. Please do not reply.</p>' .
                            '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';


                //error handeling
                try {
                    $mail->send();
                    
                        $msg = "Booking successful. Your booking for " . $date . " at " . $time . " has been recorded. You can followup your booking status by";
                        $redirectUrl = "c-booking.php?garageId=$garageId&vehiId=$vehiId&id=" . urlencode($msg);
                        header("Location: $redirectUrl");
                } catch (Exception $e) {
                    
                    $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
                    header("Location:c-booking.php?garageId=$garageId&vehiId=$vehiId&id=$msg");
                }
                
                
                exit();
        
    }
}

mysqli_close($conn);
}
?>