<?php
require_once("../include/sessionmanagement.php");
require_once("../include/dbconnection.php");
require "../vendor/autoload.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;


if (isset($_SESSION['nic'])) {
    $cusid=$_SESSION['cid'];
    $cus_fname=$_SESSION['fname'];
    $email=$_SESSION['email'];
} else {
    echo "NIC value not found.";
}


if (isset($_GET['bookingId'])) {
    $bookingId = $_GET['bookingId'];
}else {
    echo "bookingid value not found.";
}

 
    $sqlget = "SELECT * FROM booking 
    WHERE bookingId='$bookingId'";
    $resultget = mysqli_query($conn, $sqlget);

    
    if (mysqli_num_rows($resultget) > 0) {
            
            $rowresult = mysqli_fetch_assoc($resultget);
        
            $bookingdate=$rowresult['bookingDate']; 
            $timeslot=$rowresult['timeSlot']; 
            $cusid=$rowresult['cusId']; 
            $garageid=$rowresult['garageId'];
            $vehiid=$rowresult['vehiId'];  
            $payid=$rowresult['payId']; 
            $paystatus=$rowresult['pStatus']; 
        }
                                                
            $currentDate= date("Y-m-d");
            $cancelby="customer";
    
            //insert cancel booking table
            $sql = "INSERT INTO cancel_booking (cancelId, bookingId, bookingDate, timeSlot, cusId, garageId, vehiId, payId, pStatus, cancelDate, cancelBy) VALUES ('','$bookingId', '$bookingdate', '$timeslot','$cusid','$garageid','$vehiid','$payid','$paystatus','$currentDate','$cancelby')";
            $result = mysqli_query($conn, $sql) or die(mysqli_error($conn));
        
            //error handelling
            if (!$result) {
               die("Error: " . mysqli_error($conn));
                }

            //delete booking (booking and issue_certicaten table)
            if ($result) {

           
            $sqldelete =   "DELETE booking, issued_certificate
                            FROM booking
                            INNER JOIN issued_certificate ON booking.bookingId = issued_certificate.bookingId
                            WHERE booking.bookingId ='$bookingId'";

            $resultdelete=mysqli_query($conn,$sqldelete) or die(mysqli_error($conn));

               //error handelling
                if (!$resultdelete) {
                   die("Error: " . mysqli_error($conn));
                }

                    //email notification
                    $mail = new PHPMailer(true);
                    $mail ->isSMTP();
                    $mail ->SMTPAuth = true;
                    
                    $mail ->Host = "smtp.gmail.com";
                    $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
                    $mail ->Port = 587;
                  
                    $mail ->Username = "wcvfeisproject@gmail.com";
                    $mail ->Password = "xzll euej xvli frza";

                    $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
                    $mail ->addAddress($email,$cus_fname);
                    $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
                    date_default_timezone_set('Asia/kolkata');
                    $mail->isHTML(true); 

                    $mail->Body = '<p><strong>Your Reservation canceled successfully . Any payment you made will not be refunded</strong></p>' .
                                '<p>This email is automatically generated by the system. Please do not reply.</p>' .
                                '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';

                    try {
                        $mail->send();
                     
                            $msg ="Booking ( Booking ID:". $bookingId . ") canceled successfully.";	
                            header("Location:c-status.php?id=$msg"); 
                            exit();
                    } catch (Exception $e) {
                      
                        $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
                        header("Location:c-status.php?id=$msg");
                    }
                     exit();

              
} else {
    $msg = "Failed to cancel booking"; 	
    header("Location:c-status.php?id=$msg"); 
    exit();
    }
mysqli_close($conn);
?>
