<?php                 
require_once("../include/sessionmanagement.php");
require_once("../include/dbconnection.php");
require "../vendor/autoload.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

if (isset($_SESSION['nic'])) {
    $nic = $_SESSION['nic'];
    $cusid=$_SESSION['cid'];
    $cus_fname=$_SESSION['fname'];
    $email=$_SESSION['email'];
} else {
    echo "NIC value not found.";
}

 if ($_SERVER["REQUEST_METHOD"] == "POST") {
    if (isset($_POST["bookingid"])) {
        $bookingid = $_POST["bookingid"];
        $vehiid = $_POST["vehiid"];

    // check availability 
    $sql = "SELECT * FROM payment WHERE bookingId = '$bookingid'";
    $result = mysqli_query($conn, $sql);
    
        if (mysqli_num_rows($result) > 0) {
            // already paid
            $msg = "Your already pay for the booking";
            $redirectUrl = "c-payment.php?bookingid=$bookingid&vehiId=$vehiId&id=" . urlencode($msg);
            header("Location: $redirectUrl");
        } else {
                // not paid
                $amount ="1000" ;
                $payType = "Card-Online";
                $currentDate= date("Y-m-d");
                $aprovedBy="customer-online";

                    $sqlinsert = "INSERT INTO payment (payId, bookingId, vehiId, cusId, amount, payType, pDate, aprovedBy ) VALUES ('','$bookingid', '$vehiid','$cusid','$amount','$payType','$currentDate','$aprovedBy')";
                    $resultinsert = mysqli_query($conn, $sqlinsert);

                    //last id
                    $payId = mysqli_insert_id($conn);
                    $pStatus = "Complete";
                    
                    $sqlupdate = "UPDATE booking SET payId = '$payId',
                                  pStatus='$pStatus' 
                                  WHERE bookingId = $bookingid";
                 
                    $resultupdate=mysqli_query($conn,$sqlupdate);
                 
                      //email notification
                      $mail = new PHPMailer(true);
                      $mail ->isSMTP();
                      $mail ->SMTPAuth = true;
                      
                      $mail ->Host = "smtp.gmail.com";
                      $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
                      $mail ->Port = 587;

                      $mail ->Username = "wcvfeisproject@gmail.com";
                      $mail ->Password = "xzll euej xvli frza";

                      $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
                      $mail ->addAddress($email,$cus_fname);
                      $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
                      date_default_timezone_set('Asia/kolkata');
                      $mail->isHTML(true);

                      $mail->Body = '<p><strong>"Payment successful. Your booking ID :'. $bookingid.' "</strong></p>' .
                                  '<p>This email is automatically generated by the system. Please do not reply.</p>' .
                                  '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';
                      //error handeling
                      try {
                          $mail->send();
                          
                                $msg = "Payment successful. Your booking ID :.$bookingid.";
                                $redirectUrl = "c-status.php?garageId=$garageId&vehiId=$vehiId&id=" . urlencode($msg);
                                 header("Location: $redirectUrl");
                      } catch (Exception $e) {
                          
                          $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
                          header("Location:../c-booking.php?id=$msg");
                      }                
                      exit();
            }
            mysqli_close($conn);
    }else {
         echo "value not found.";
    }
}
?>
      
        