<?php
require_once("../include/session.php");
require_once("../include/sessionmanagementdmt.php");
require_once("../include/dbconnection.php");
  
//email 
require "../vendor/autoload.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

if (isset($_SESSION['stfNic'])) {
    $stfFname = $_SESSION['stfFname'];
    $stflLname = $_SESSION['stflLname'];
    $stfRole = $_SESSION['stfRole'];
} else {
    echo "NIC value not found.";
}


if ($_SERVER["REQUEST_METHOD"] == "POST") {
 
    if (isset($_POST["new_status"])) {
        $garage_ststus = $_POST["garage_stasus"];
        $garage_id = $_POST["garage_id"];
        $garage_name = $_POST["garage_name"];
        $garage_email= $_POST["garage_email"];
        $new_status = $_POST["new_status"]; 
    }else {
        echo "value not found.";
}
}

    $today=date('Y-m-d'); 
    //new state send by form value
        if($garage_ststus == 'Active'){ 
            $sqlup = "UPDATE garage SET gStatus = '$new_status', registredBy='$stflLname', registredDate='$today' WHERE garageId = $garage_id";
            
            $resultin=mysqli_query($conn,$sqlup) or die(mysqli_error($conn));

            //email notification
            $mail = new PHPMailer(true);
            $mail ->isSMTP();
            $mail ->SMTPAuth = true;

            $mail ->Host = "smtp.gmail.com";
            $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
            $mail ->Port = 587;
           
            $mail ->Username = "wcvfeisproject@gmail.com";
            $mail ->Password = "xzll euej xvli frza";

            $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
            $mail ->addAddress($garage_email,$garage_name);
            $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
            date_default_timezone_set('Asia/kolkata');
            $mail->isHTML(true); 
        
            $mail->Body = '<p><strong>Unfortunately, your garage'.' '. $garage_name .' '.' has been temporarily suspended for the authorization of issuing a Vehicle Fitness Certificate.. Please contact Department of Mortor Traffic</strong></p>'.
                        '<p>Authorized: ' .$stfFname .''.$stflLname. '</p>'.
                        '<p>Date: '. date('Y-m-d') . '</p>'.
                        '<p>Designation: '.$stfRole. '</p>'.
                        '<p>This email is automatically generated by the system. Please do not reply.</p>'.
                        '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';

            //error handeling
            try {
                $mail->send();
                
                    $msg =". $garage_name .'Operational status has been succsessfully Updated";	
                    header("Location:d-garagemgt.php?id=$msg"); 
                    exit();
            } catch (Exception $e) {
               
                $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
                header("Location:g-garagemgt.php?id=$msg");
            }
            exit();

            
        }elseif ($garage_ststus == 'Suspend'){
            $sqlup = "UPDATE garage SET gStatus = '$new_status' , registredBy='$stflLname', registredDate='$today' WHERE garageId = $garage_id";
            
            $resultin=mysqli_query($conn,$sqlup) or die(mysqli_error($conn));
            
          //email notification
          $mail = new PHPMailer(true);
          $mail ->isSMTP();
          $mail ->SMTPAuth = true;

          $mail ->Host = "smtp.gmail.com";
          $mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
          $mail ->Port = 587;
      
          $mail ->Username = "wcvfeisproject@gmail.com";
          $mail ->Password = "xzll euej xvli frza";

          $mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
          $mail ->addAddress($garage_email,$garage_name);
          $mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
          date_default_timezone_set('Asia/kolkata');
          $mail->isHTML(true); 

          $mail->Body = '<p><strong> your garage'.' '. $garage_name .' '.' has been Active for the authorization of issuing a Vehicle Fitness Certificate.. Please contact Department of Mortor Traffic</strong></p>'.
                      '<p>Authorized:' .$stfFname .''.$stflLname. '</p>'.
                      '<p>Date: '. date('Y-m-d') . '</p>'.
                      '<p>Designation: '.$stfRole. '</p>'.
                      '<p>This email is automatically generated by the system. Please do not reply.</p>'.
                      '<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';


          //error handeling
          try {
              $mail->send();
                  $msg =". $garage_name .'Operational status has been succsessfully Updated";	
                  header("Location:d-garagemgt.php?id=$msg"); 
                  exit();
          } catch (Exception $e) {
              $msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
              header("Location:g-garagemgt.php?id=$msg");
          }
          exit();
        }
?>
