<?php
require_once("../../include/session.php");
require_once("../../include/dbconnection.php");
require "../../vendor/autoload.php";
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

if (isset($_POST["submit"])){
   if($_POST['email']== "" || $_POST['password']== ""){
       $msg=("User Name or Password can not be empty....");
       header("Location:../g-login.php?id=$msg");	
	   exit();
   }

$email=mysqli_real_escape_string($conn,$_POST['email']);
$pass=mysqli_real_escape_string($conn,$_POST['password']);
$role=mysqli_real_escape_string($conn,$_POST['role']);
$epass=sha1($pass);

$sql=mysqli_query($conn,"SELECT * FROM garage_user as gu, garage_login as gl 
	WHERE gl.email ='$email'AND gl.pwd='$epass' AND gu.userId=gl.userId AND gu.roleId=$role");
$count=mysqli_num_rows($sql);
//echo $count;
if($count!=0){
	$sqlinfo="SELECT * FROM garage_user as gu, garage_login as gl
	WHERE gl.email ='$email' AND gu.userId=gl.userId AND gu.roleId=$role";
	
	$resultinfo=mysqli_query($conn,$sqlinfo);
	$rowinfo=mysqli_fetch_array($resultinfo);
	
//set session variable	
	$_SESSION['garageId']=$rowinfo['garageId'];
	$_SESSION['roleId']=$rowinfo['roleId'];
	$usernic=$_SESSION['unic']=$rowinfo['userNic'];
	$_SESSION['email']=$rowinfo['email'];
	$_SESSION['userId']=$rowinfo['userId'];
    $_SESSION['password']=$rowinfo['pwd'];
	$_SESSION['sidgarage']=session_id(); 
	
	//email notification
	$mail = new PHPMailer(true);
	$mail ->isSMTP();
	$mail ->SMTPAuth = true;
	
	$mail ->Host = "smtp.gmail.com";
	$mail ->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
	$mail ->Port = 587;
	
	$mail ->Username = "wcvfeisproject@gmail.com";
	$mail ->Password = "xzll euej xvli frza";

	$mail ->setFrom("wcvfeisproject@gmail.com","WCVFEIS");
	//$mail ->addAddress($rowinfo['email'],$rowinfo['cusFname']);
	$mail ->addAddress($rowinfo['email']);
	$mail ->Subject = "Notification from Commercial Vechicle Fitness e-certificate Issuing System";
	date_default_timezone_set('Asia/kolkata');
	$mail->isHTML(true); 
	$mail->Body = '<p><strong>You are successfully logged in.</strong></p>' .
				'<p>This email is automatically generated by the system. Please do not reply.</p>' .
				'<p>Log time: ' . date('Y-m-d H:i:s') . '</p>';

	//error handeling
	try {
		$mail->send();
		header("Location:../g-dashboard.php");
	} catch (Exception $e) {
		$msg = "Message could not be sent. Mailer Error: " . $mail->ErrorInfo;
		header("Location:../g-dashboard.php?id=$msg");
	}	
}else{
	$msg=("Invalid User Name or Password or Role....");
	header("Location:../g-login.php?id=$msg");
	exit(); 
}
}
?>

